
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.hua.dit;

import java_cup.runtime.Symbol;
import java.util.List;
import java.util.LinkedList;
import org.hua.dit.ast.*;
import org.hua.dit.types.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Symbols.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\110\000\002\002\004\000\002\023\003\000\002\022" +
    "\005\000\002\020\011\000\002\030\002\000\002\030\005" +
    "\000\002\014\002\000\002\014\005\000\002\014\005\000" +
    "\002\014\004\000\002\002\003\000\002\002\003\000\002" +
    "\011\003\000\002\011\006\000\002\015\004\000\002\015" +
    "\004\000\002\013\003\000\002\013\005\000\002\013\006" +
    "\000\002\026\002\000\002\026\004\000\002\012\003\000" +
    "\002\012\003\000\002\012\003\000\002\010\010\000\002" +
    "\025\002\000\002\025\004\000\002\007\004\000\002\021" +
    "\004\000\002\005\003\000\002\005\006\000\002\005\003" +
    "\000\002\005\004\000\002\005\010\000\002\005\006\000" +
    "\002\005\006\000\002\005\004\000\002\005\005\000\002" +
    "\005\003\000\002\006\005\000\002\024\002\000\002\024" +
    "\004\000\002\017\005\000\002\017\007\000\002\027\002" +
    "\000\002\027\005\000\002\016\003\000\002\016\003\000" +
    "\002\016\006\000\002\003\003\000\002\003\003\000\002" +
    "\003\003\000\002\003\003\000\002\003\005\000\002\003" +
    "\004\000\002\003\004\000\002\003\005\000\002\003\005" +
    "\000\002\003\005\000\002\003\005\000\002\003\005\000" +
    "\002\003\003\000\002\004\005\000\002\004\004\000\002" +
    "\004\005\000\002\004\005\000\002\004\005\000\002\004" +
    "\005\000\002\004\005\000\002\004\005\000\002\004\005" +
    "\000\002\004\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\210\000\004\011\004\001\002\000\004\056\164\001" +
    "\002\000\004\002\163\001\002\000\004\002\000\001\002" +
    "\000\010\011\uffee\023\uffee\044\uffee\001\002\000\010\011" +
    "\004\023\020\044\011\001\002\000\024\012\uffd9\021\uffd9" +
    "\023\uffd9\024\uffd9\044\uffd9\045\uffd9\047\uffd9\056\uffd9\061" +
    "\uffd9\001\002\000\010\011\uffed\023\uffed\044\uffed\001\002" +
    "\000\010\011\uffea\023\uffea\044\uffea\001\002\000\012\002" +
    "\uffff\011\uffff\023\uffff\044\uffff\001\002\000\012\011\uffee" +
    "\023\uffee\044\uffee\047\037\001\002\000\010\011\uffeb\023" +
    "\uffeb\044\uffeb\001\002\000\010\011\uffec\023\uffec\044\uffec" +
    "\001\002\000\004\056\021\001\002\000\006\046\uffe8\050" +
    "\uffe8\001\002\000\006\046\023\050\024\001\002\000\004" +
    "\056\036\001\002\000\006\005\030\013\026\001\002\000" +
    "\006\046\uffe7\050\uffe7\001\002\000\016\011\ufff7\023\ufff7" +
    "\041\ufff7\042\ufff7\044\ufff7\047\ufff7\001\002\000\006\042" +
    "\033\047\032\001\002\000\016\011\ufff6\023\ufff6\041\ufff6" +
    "\042\ufff6\044\ufff6\047\ufff6\001\002\000\006\042\ufff5\047" +
    "\ufff5\001\002\000\030\010\uffe9\011\uffe9\012\uffe9\021\uffe9" +
    "\023\uffe9\024\uffe9\044\uffe9\045\uffe9\047\uffe9\056\uffe9\061" +
    "\uffe9\001\002\000\004\057\034\001\002\000\004\043\035" +
    "\001\002\000\006\042\ufff4\047\ufff4\001\002\000\006\046" +
    "\uffe6\050\uffe6\001\002\000\010\011\uffe5\023\uffe5\044\uffe5" +
    "\001\002\000\024\012\052\021\043\023\020\024\042\044" +
    "\011\045\054\047\050\056\053\061\041\001\002\000\054" +
    "\004\uffd2\006\uffd2\007\uffd2\014\uffd2\017\uffd2\022\uffd2\025" +
    "\uffd2\026\uffd2\027\uffd2\031\uffd2\032\uffd2\034\uffd2\035\uffd2" +
    "\036\uffd2\037\uffd2\041\uffd2\042\uffd2\043\uffd2\046\uffd2\047" +
    "\uffd2\051\uffd2\001\002\000\024\015\116\025\060\026\061" +
    "\040\115\056\053\057\062\060\056\061\041\064\065\001" +
    "\002\000\024\025\060\026\061\040\057\047\155\056\053" +
    "\057\062\060\056\061\041\064\065\001\002\000\024\012" +
    "\uffd8\021\uffd8\023\uffd8\024\uffd8\044\uffd8\045\uffd8\047\uffd8" +
    "\056\uffd8\061\uffd8\001\002\000\026\010\uffe2\012\uffe2\021" +
    "\uffe2\023\uffe2\024\uffe2\044\uffe2\045\uffe2\047\uffe2\056\uffe2" +
    "\061\uffe2\001\002\000\026\010\uffdb\012\uffdb\021\uffdb\023" +
    "\uffdb\024\uffdb\044\uffdb\045\uffdb\047\uffdb\056\uffdb\061\uffdb" +
    "\001\002\000\006\042\106\051\152\001\002\000\026\010" +
    "\uffe4\012\uffe4\021\uffe4\023\uffe4\024\uffe4\044\uffe4\045\uffe4" +
    "\047\uffe4\056\uffe4\061\uffe4\001\002\000\004\047\151\001" +
    "\002\000\024\015\116\025\060\026\061\040\115\056\053" +
    "\057\062\060\056\061\041\064\065\001\002\000\056\004" +
    "\uffd3\006\uffd3\007\uffd3\014\uffd3\017\uffd3\022\uffd3\025\uffd3" +
    "\026\uffd3\027\uffd3\031\uffd3\032\uffd3\034\uffd3\035\uffd3\036" +
    "\uffd3\037\uffd3\040\055\041\uffd3\042\uffd3\043\uffd3\046\uffd3" +
    "\047\uffd3\051\uffd3\001\002\000\032\002\uffda\010\uffda\011" +
    "\uffda\012\uffda\021\uffda\023\uffda\024\uffda\044\uffda\045\uffda" +
    "\047\uffda\056\uffda\061\uffda\001\002\000\024\025\060\026" +
    "\061\040\057\041\064\056\053\057\062\060\056\061\041" +
    "\064\065\001\002\000\050\004\uffcf\006\uffcf\007\uffcf\014" +
    "\uffcf\017\uffcf\022\uffcf\025\uffcf\026\uffcf\027\uffcf\031\uffcf" +
    "\032\uffcf\034\uffcf\035\uffcf\036\uffcf\037\uffcf\041\uffcf\043" +
    "\uffcf\046\uffcf\047\uffcf\001\002\000\022\025\060\026\061" +
    "\040\057\056\053\057\062\060\056\061\041\064\065\001" +
    "\002\000\022\025\060\026\061\040\057\056\053\057\062" +
    "\060\056\061\041\064\065\001\002\000\022\025\060\026" +
    "\061\040\057\056\053\057\062\060\056\061\041\064\065" +
    "\001\002\000\050\004\uffd0\006\uffd0\007\uffd0\014\uffd0\017" +
    "\uffd0\022\uffd0\025\uffd0\026\uffd0\027\uffd0\031\uffd0\032\uffd0" +
    "\034\uffd0\035\uffd0\036\uffd0\037\uffd0\041\uffd0\043\uffd0\046" +
    "\uffd0\047\uffd0\001\002\000\052\004\uffce\006\uffce\007\uffce" +
    "\014\uffce\017\uffce\022\uffce\025\uffce\026\uffce\027\uffce\031" +
    "\uffce\032\uffce\034\uffce\035\uffce\036\uffce\037\uffce\041\uffce" +
    "\042\106\043\uffce\046\uffce\047\uffce\001\002\000\050\004" +
    "\uffd7\006\uffd7\007\uffd7\014\uffd7\017\uffd7\022\uffd7\025\uffd7" +
    "\026\uffd7\027\uffd7\031\uffd7\032\uffd7\034\uffd7\035\uffd7\036" +
    "\uffd7\037\uffd7\041\uffd7\043\uffd7\046\uffd7\047\uffd7\001\002" +
    "\000\050\004\uffc4\006\uffc4\007\uffc4\014\uffc4\017\uffc4\022" +
    "\uffc4\025\uffc4\026\uffc4\027\uffc4\031\uffc4\032\uffc4\034\uffc4" +
    "\035\uffc4\036\uffc4\037\uffc4\041\uffc4\043\uffc4\046\uffc4\047" +
    "\uffc4\001\002\000\050\004\uffcd\006\uffcd\007\uffcd\014\uffcd" +
    "\017\uffcd\022\uffcd\025\uffcd\026\uffcd\027\uffcd\031\uffcd\032" +
    "\uffcd\034\uffcd\035\uffcd\036\uffcd\037\uffcd\041\uffcd\043\uffcd" +
    "\046\uffcd\047\uffcd\001\002\000\020\006\075\014\072\025" +
    "\071\026\073\027\070\041\uffd5\046\uffd5\001\002\000\022" +
    "\025\060\026\061\040\057\056\053\057\062\060\056\061" +
    "\041\064\065\001\002\000\022\025\060\026\061\040\057" +
    "\056\053\057\062\060\056\061\041\064\065\001\002\000" +
    "\022\025\060\026\061\040\057\056\053\057\062\060\056" +
    "\061\041\064\065\001\002\000\022\025\060\026\061\040" +
    "\057\056\053\057\062\060\056\061\041\064\065\001\002" +
    "\000\006\041\100\046\077\001\002\000\022\025\060\026" +
    "\061\040\057\056\053\057\062\060\056\061\041\064\065" +
    "\001\002\000\050\004\uffc6\006\uffc6\007\uffc6\014\uffc6\017" +
    "\uffc6\022\uffc6\025\071\026\073\027\uffc6\031\uffc6\032\uffc6" +
    "\034\uffc6\035\uffc6\036\uffc6\037\uffc6\041\uffc6\043\uffc6\046" +
    "\uffc6\047\uffc6\001\002\000\022\025\060\026\061\040\057" +
    "\056\053\057\062\060\056\061\041\064\065\001\002\000" +
    "\050\004\uffd6\006\uffd6\007\uffd6\014\uffd6\017\uffd6\022\uffd6" +
    "\025\uffd6\026\uffd6\027\uffd6\031\uffd6\032\uffd6\034\uffd6\035" +
    "\uffd6\036\uffd6\037\uffd6\041\uffd6\043\uffd6\046\uffd6\047\uffd6" +
    "\001\002\000\020\006\075\014\072\025\071\026\073\027" +
    "\070\041\uffd4\046\uffd4\001\002\000\050\004\uffc8\006\uffc8" +
    "\007\uffc8\014\uffc8\017\uffc8\022\uffc8\025\uffc8\026\uffc8\027" +
    "\uffc8\031\uffc8\032\uffc8\034\uffc8\035\uffc8\036\uffc8\037\uffc8" +
    "\041\uffc8\043\uffc8\046\uffc8\047\uffc8\001\002\000\050\004" +
    "\uffc5\006\uffc5\007\uffc5\014\uffc5\017\uffc5\022\uffc5\025\071" +
    "\026\073\027\uffc5\031\uffc5\032\uffc5\034\uffc5\035\uffc5\036" +
    "\uffc5\037\uffc5\041\uffc5\043\uffc5\046\uffc5\047\uffc5\001\002" +
    "\000\050\004\uffc9\006\uffc9\007\uffc9\014\uffc9\017\uffc9\022" +
    "\uffc9\025\uffc9\026\uffc9\027\uffc9\031\uffc9\032\uffc9\034\uffc9" +
    "\035\uffc9\036\uffc9\037\uffc9\041\uffc9\043\uffc9\046\uffc9\047" +
    "\uffc9\001\002\000\050\004\uffc7\006\uffc7\007\uffc7\014\uffc7" +
    "\017\uffc7\022\uffc7\025\071\026\073\027\uffc7\031\uffc7\032" +
    "\uffc7\034\uffc7\035\uffc7\036\uffc7\037\uffc7\041\uffc7\043\uffc7" +
    "\046\uffc7\047\uffc7\001\002\000\022\025\060\026\061\040" +
    "\057\056\053\057\062\060\056\061\041\064\065\001\002" +
    "\000\016\006\075\014\072\025\071\026\073\027\070\043" +
    "\110\001\002\000\054\004\uffd1\006\uffd1\007\uffd1\014\uffd1" +
    "\017\uffd1\022\uffd1\025\uffd1\026\uffd1\027\uffd1\031\uffd1\032" +
    "\uffd1\034\uffd1\035\uffd1\036\uffd1\037\uffd1\041\uffd1\042\uffd1" +
    "\043\uffd1\046\uffd1\047\uffd1\051\uffd1\001\002\000\050\004" +
    "\uffca\006\uffca\007\uffca\014\uffca\017\uffca\022\uffca\025\uffca" +
    "\026\uffca\027\uffca\031\uffca\032\uffca\034\uffca\035\uffca\036" +
    "\uffca\037\uffca\041\uffca\043\uffca\046\uffca\047\uffca\001\002" +
    "\000\050\004\uffcb\006\uffcb\007\uffcb\014\uffcb\017\uffcb\022" +
    "\uffcb\025\uffcb\026\uffcb\027\uffcb\031\uffcb\032\uffcb\034\uffcb" +
    "\035\uffcb\036\uffcb\037\uffcb\041\uffcb\043\uffcb\046\uffcb\047" +
    "\uffcb\001\002\000\016\006\075\014\072\025\071\026\073" +
    "\027\070\041\114\001\002\000\050\004\uffcc\006\uffcc\007" +
    "\uffcc\014\uffcc\017\uffcc\022\uffcc\025\uffcc\026\uffcc\027\uffcc" +
    "\031\uffcc\032\uffcc\034\uffcc\035\uffcc\036\uffcc\037\uffcc\041" +
    "\uffcc\043\uffcc\046\uffcc\047\uffcc\001\002\000\024\015\116" +
    "\025\060\026\061\040\115\056\053\057\062\060\056\061" +
    "\041\064\065\001\002\000\024\015\116\025\060\026\061" +
    "\040\115\056\053\057\062\060\056\061\041\064\065\001" +
    "\002\000\010\004\137\017\136\022\135\001\002\000\030" +
    "\006\075\014\072\025\071\026\073\027\070\031\123\032" +
    "\125\034\124\035\122\036\121\037\126\001\002\000\022" +
    "\025\060\026\061\040\057\056\053\057\062\060\056\061" +
    "\041\064\065\001\002\000\022\025\060\026\061\040\057" +
    "\056\053\057\062\060\056\061\041\064\065\001\002\000" +
    "\022\025\060\026\061\040\057\056\053\057\062\060\056" +
    "\061\041\064\065\001\002\000\022\025\060\026\061\040" +
    "\057\056\053\057\062\060\056\061\041\064\065\001\002" +
    "\000\022\025\060\026\061\040\057\056\053\057\062\060" +
    "\056\061\041\064\065\001\002\000\022\025\060\026\061" +
    "\040\057\056\053\057\062\060\056\061\041\064\065\001" +
    "\002\000\026\004\uffba\006\075\007\uffba\014\072\017\uffba" +
    "\022\uffba\025\071\026\073\027\070\041\uffba\001\002\000" +
    "\026\004\uffbf\006\075\007\uffbf\014\072\017\uffbf\022\uffbf" +
    "\025\071\026\073\027\070\041\uffbf\001\002\000\026\004" +
    "\uffbd\006\075\007\uffbd\014\072\017\uffbd\022\uffbd\025\071" +
    "\026\073\027\070\041\uffbd\001\002\000\026\004\uffbe\006" +
    "\075\007\uffbe\014\072\017\uffbe\022\uffbe\025\071\026\073" +
    "\027\070\041\uffbe\001\002\000\026\004\uffbc\006\075\007" +
    "\uffbc\014\072\017\uffbc\022\uffbc\025\071\026\073\027\070" +
    "\041\uffbc\001\002\000\026\004\uffbb\006\075\007\uffbb\014" +
    "\072\017\uffbb\022\uffbb\025\071\026\073\027\070\041\uffbb" +
    "\001\002\000\022\012\052\021\043\023\020\024\042\044" +
    "\011\047\050\056\053\061\041\001\002\000\024\015\116" +
    "\025\060\026\061\040\115\056\053\057\062\060\056\061" +
    "\041\064\065\001\002\000\024\015\116\025\060\026\061" +
    "\040\115\056\053\057\062\060\056\061\041\064\065\001" +
    "\002\000\014\004\uffc1\007\uffc1\017\uffc1\022\uffc1\041\uffc1" +
    "\001\002\000\014\004\uffc0\007\uffc0\017\uffc0\022\uffc0\041" +
    "\uffc0\001\002\000\026\010\143\012\uffdf\021\uffdf\023\uffdf" +
    "\024\uffdf\044\uffdf\045\uffdf\047\uffdf\056\uffdf\061\uffdf\001" +
    "\002\000\022\012\052\021\043\023\020\024\042\044\011" +
    "\047\050\056\053\061\041\001\002\000\026\010\uffe0\012" +
    "\uffe0\021\uffe0\023\uffe0\024\uffe0\044\uffe0\045\uffe0\047\uffe0" +
    "\056\uffe0\061\uffe0\001\002\000\014\004\uffc2\007\uffc2\017" +
    "\uffc2\022\uffc2\041\uffc2\001\002\000\010\004\137\017\136" +
    "\041\150\001\002\000\032\006\075\014\072\025\071\026" +
    "\073\027\070\031\123\032\125\034\124\035\122\036\121" +
    "\037\126\041\114\001\002\000\014\004\uffc3\007\uffc3\017" +
    "\uffc3\022\uffc3\041\uffc3\001\002\000\026\010\uffe1\012\uffe1" +
    "\021\uffe1\023\uffe1\024\uffe1\044\uffe1\045\uffe1\047\uffe1\056" +
    "\uffe1\061\uffe1\001\002\000\022\025\060\026\061\040\057" +
    "\056\053\057\062\060\056\061\041\064\065\001\002\000" +
    "\016\006\075\014\072\025\071\026\073\027\070\047\154" +
    "\001\002\000\026\010\uffe3\012\uffe3\021\uffe3\023\uffe3\024" +
    "\uffe3\044\uffe3\045\uffe3\047\uffe3\056\uffe3\061\uffe3\001\002" +
    "\000\026\010\uffdd\012\uffdd\021\uffdd\023\uffdd\024\uffdd\044" +
    "\uffdd\045\uffdd\047\uffdd\056\uffdd\061\uffdd\001\002\000\016" +
    "\006\075\014\072\025\071\026\073\027\070\047\157\001" +
    "\002\000\026\010\uffdc\012\uffdc\021\uffdc\023\uffdc\024\uffdc" +
    "\044\uffdc\045\uffdc\047\uffdc\056\uffdc\061\uffdc\001\002\000" +
    "\010\004\137\007\161\017\136\001\002\000\022\012\052" +
    "\021\043\023\020\024\042\044\011\047\050\056\053\061" +
    "\041\001\002\000\026\010\uffde\012\uffde\021\uffde\023\uffde" +
    "\024\uffde\044\uffde\045\uffde\047\uffde\056\uffde\061\uffde\001" +
    "\002\000\004\002\001\001\002\000\004\040\165\001\002" +
    "\000\012\020\166\041\ufffb\047\ufffb\056\167\001\002\000" +
    "\012\020\166\041\ufffb\047\ufffb\056\167\001\002\000\006" +
    "\046\201\050\202\001\002\000\006\041\ufffd\047\ufffd\001" +
    "\002\000\006\041\173\047\172\001\002\000\012\020\166" +
    "\041\ufffb\047\ufffb\056\167\001\002\000\004\050\174\001" +
    "\002\000\010\005\030\013\026\016\176\001\002\000\012" +
    "\011\ufffe\023\ufffe\044\ufffe\047\ufffe\001\002\000\012\011" +
    "\ufff2\023\ufff2\044\ufff2\047\ufff2\001\002\000\012\011\ufff3" +
    "\023\ufff3\044\ufff3\047\ufff3\001\002\000\006\041\ufffc\047" +
    "\ufffc\001\002\000\012\020\166\041\ufffb\047\ufffb\056\167" +
    "\001\002\000\006\005\030\013\026\001\002\000\006\041" +
    "\ufffa\047\ufffa\001\002\000\010\041\ufff1\042\205\047\ufff1" +
    "\001\002\000\006\043\206\057\207\001\002\000\006\041" +
    "\ufff0\047\ufff0\001\002\000\004\043\210\001\002\000\006" +
    "\041\uffef\047\uffef\001\002\000\006\041\ufff9\047\ufff9\001" +
    "\002\000\006\041\ufff8\047\ufff8\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\210\000\010\020\006\022\005\023\004\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\026\007\001\001\000\016\006\013\010\012\012\011\020" +
    "\014\021\015\022\016\001\001\000\004\024\037\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\026\007\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\025\021\001\001\000\004\007" +
    "\024\001\001\000\002\001\001\000\006\002\030\011\026" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\014\005\043\006\044" +
    "\010\045\016\046\017\050\001\001\000\002\001\001\000" +
    "\012\003\117\004\157\016\062\017\065\001\001\000\010" +
    "\003\155\016\062\017\065\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\003\117\004\116\016" +
    "\062\017\065\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\003\066\016\062\017\065\001\001\000\002\001" +
    "\001\000\010\003\112\016\062\017\065\001\001\000\010" +
    "\003\111\016\062\017\065\001\001\000\010\003\110\016" +
    "\062\017\065\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\027\073\001\001\000\010\003\104\016\062\017\065" +
    "\001\001\000\010\003\103\016\062\017\065\001\001\000" +
    "\010\003\102\016\062\017\065\001\001\000\010\003\101" +
    "\016\062\017\065\001\001\000\002\001\001\000\010\003" +
    "\075\016\062\017\065\001\001\000\002\001\001\000\010" +
    "\003\100\016\062\017\065\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\003\106\016\062\017" +
    "\065\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\003\146\004\145\016\062\017\065\001\001" +
    "\000\012\003\117\004\144\016\062\017\065\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\003\133\016\062" +
    "\017\065\001\001\000\010\003\132\016\062\017\065\001" +
    "\001\000\010\003\131\016\062\017\065\001\001\000\010" +
    "\003\130\016\062\017\065\001\001\000\010\003\127\016" +
    "\062\017\065\001\001\000\010\003\126\016\062\017\065" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\014\005\141\006\044\010\045\016\046\017\050\001" +
    "\001\000\012\003\117\004\140\016\062\017\065\001\001" +
    "\000\012\003\117\004\137\016\062\017\065\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\014" +
    "\005\143\006\044\010\045\016\046\017\050\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\003" +
    "\152\016\062\017\065\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\014\005\161\006\044\010\045" +
    "\016\046\017\050\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\014\167\001\001\000\004" +
    "\014\211\001\001\000\002\001\001\000\004\030\170\001" +
    "\001\000\002\001\001\000\004\014\177\001\001\000\004" +
    "\015\174\001\001\000\004\002\176\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\014\210\001\001\000\006\002\203\013\202\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Program start_val = (Program)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= func_def 
            {
              Program RESULT =null;
		int fdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		FuncDef fd = (FuncDef)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Program(fd); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // func_def ::= header local_def_list block 
            {
              FuncDef RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Header h = (Header)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int ldlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int ldlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		java.util.List<LocalDef> ldl = (java.util.List<LocalDef>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Block b = (Block)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new FuncDef(h, ldl, b); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("func_def",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // header ::= T_fun T_id T_lpar fpar_def semicolon_fpar_def_list T_rpar ret_type 
            {
              Header RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		java.lang.String id = (java.lang.String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int fpdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int fpdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		FparDef fpd = (FparDef)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int sfpdlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int sfpdlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		java.util.List<FparDef> sfpdl = (java.util.List<FparDef>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int rtleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rtright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		RetType rt = (RetType)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Header(id, fpd, sfpdl, rt); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("header",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // semicolon_fpar_def_list ::= 
            {
              java.util.List<FparDef> RESULT =null;
		 RESULT = new LinkedList<FparDef>(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("semicolon_fpar_def_list",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // semicolon_fpar_def_list ::= semicolon_fpar_def_list T_semicolon fpar_def 
            {
              java.util.List<FparDef> RESULT =null;
		int sfpdlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int sfpdlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		java.util.List<FparDef> sfpdl = (java.util.List<FparDef>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int fpdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fpdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		FparDef fpd = (FparDef)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 sfpdl.add(fpd); RESULT = sfpdl; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("semicolon_fpar_def_list",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // fpar_def ::= 
            {
              FparDef RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("fpar_def",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // fpar_def ::= T_id T_colon fpar_type 
            {
              FparDef RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		java.lang.String id = (java.lang.String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Type type = (Type)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new FparDef(id, type); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("fpar_def",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // fpar_def ::= T_id T_comma fpar_def 
            {
              FparDef RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		java.lang.String id = (java.lang.String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int fpdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fpdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		FparDef fpd = (FparDef)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new FparDef(id, fpd); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("fpar_def",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // fpar_def ::= T_ref fpar_def 
            {
              FparDef RESULT =null;
		int fpdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fpdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		FparDef fpd = (FparDef)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new FparDef(fpd); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("fpar_def",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // data_type ::= T_int 
            {
              Object RESULT =null;
		 RESULT = BasicType.Int; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("data_type",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // data_type ::= T_char 
            {
              Object RESULT =null;
		 RESULT = BasicType.Char; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("data_type",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // type ::= data_type 
            {
              Type RESULT =null;
		int dtleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dtright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object dt = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = (BasicType) dt; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // type ::= type T_lbracket T_num T_rbracket 
            {
              Type RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		java.lang.Integer n = (java.lang.Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new ArrayType((BasicType) t, n); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // ret_type ::= T_colon data_type 
            {
              RetType RESULT =null;
		int dtleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dtright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object dt = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new RetType((BasicType) dt); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ret_type",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // ret_type ::= T_colon T_nothing 
            {
              RetType RESULT =null;
		 RESULT = new RetType(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ret_type",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // fpar_type ::= data_type 
            {
              Type RESULT =null;
		int dtleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dtright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object dt = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = (BasicType) dt; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("fpar_type",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // fpar_type ::= data_type T_lbracket T_rbracket 
            {
              Type RESULT =null;
		int dtleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int dtright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object dt = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 RESULT = new ArrayType((BasicType) dt); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("fpar_type",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // fpar_type ::= data_type T_lbracket T_num T_rbracket 
            {
              Type RESULT =null;
		int dtleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int dtright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object dt = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		java.lang.Integer n = (java.lang.Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new ArrayType((BasicType) dt, n); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("fpar_type",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // local_def_list ::= 
            {
              java.util.List<LocalDef> RESULT =null;
		 RESULT = new LinkedList<LocalDef>(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("local_def_list",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // local_def_list ::= local_def_list local_def 
            {
              java.util.List<LocalDef> RESULT =null;
		int ldlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int ldlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		java.util.List<LocalDef> ldl = (java.util.List<LocalDef>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int ldleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int ldright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		LocalDef ld = (LocalDef)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 ldl.add(ld); RESULT = ldl; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("local_def_list",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // local_def ::= func_def 
            {
              LocalDef RESULT =null;
		int fdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		FuncDef fd = (FuncDef)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new LocalDef(fd); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("local_def",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // local_def ::= func_decl 
            {
              LocalDef RESULT =null;
		int fdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		FuncDecl fd = (FuncDecl)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new LocalDef(fd); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("local_def",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // local_def ::= var_def 
            {
              LocalDef RESULT =null;
		int vdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		VarDef vd = (VarDef)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new LocalDef(vd); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("local_def",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // var_def ::= T_var T_id comma_id_list T_colon type T_semicolon 
            {
              VarDef RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		java.lang.String id = (java.lang.String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int cidlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int cidlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		java.util.List<CommaId> cidl = (java.util.List<CommaId>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new VarDef(id, cidl, t); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("var_def",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // comma_id_list ::= 
            {
              java.util.List<CommaId> RESULT =null;
		 RESULT = new LinkedList<CommaId>(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comma_id_list",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // comma_id_list ::= comma_id_list comma_id 
            {
              java.util.List<CommaId> RESULT =null;
		int cidlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int cidlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		java.util.List<CommaId> cidl = (java.util.List<CommaId>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int cidleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cidright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		CommaId cid = (CommaId)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 cidl.add(cid); RESULT = cidl; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comma_id_list",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // comma_id ::= T_comma T_id 
            {
              CommaId RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		java.lang.String id = (java.lang.String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new CommaId(id); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comma_id",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // func_decl ::= header T_semicolon 
            {
              FuncDecl RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Header h = (Header)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new FuncDecl(h); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("func_decl",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // stmt ::= T_semicolon 
            {
              Stmt RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // stmt ::= l_value T_larrow expr T_semicolon 
            {
              Stmt RESULT =null;
		int lvleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int lvright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		LValue lv = (LValue)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new ValueAssignment(lv, e); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // stmt ::= block 
            {
              Stmt RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Block b = (Block)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Block(b); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // stmt ::= func_call T_semicolon 
            {
              Stmt RESULT =null;
		int fcleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int fcright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		FuncCall fc = (FuncCall)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = fc; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // stmt ::= T_if cond T_then stmt T_else stmt 
            {
              Stmt RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Cond c = (Cond)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int tsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int tsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Stmt ts = (Stmt)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int esleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int esright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Stmt es = (Stmt)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new If(c, ts, es); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // stmt ::= T_if cond T_then stmt 
            {
              Stmt RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Cond c = (Cond)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new If(c, s); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // stmt ::= T_while cond T_do stmt 
            {
              Stmt RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Cond c = (Cond)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new While(c, s); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // stmt ::= T_return T_semicolon 
            {
              Stmt RESULT =null;
		 RESULT = new Return(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // stmt ::= T_return expr T_semicolon 
            {
              Stmt RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Return(e); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // stmt ::= var_def 
            {
              Stmt RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // block ::= T_lcurlybracket stmt_list T_rcurlybracket 
            {
              Block RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		java.util.List<Stmt> sl = (java.util.List<Stmt>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Block(sl); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("block",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // stmt_list ::= 
            {
              java.util.List<Stmt> RESULT =null;
		 RESULT = new LinkedList<Stmt>(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt_list",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // stmt_list ::= stmt_list stmt 
            {
              java.util.List<Stmt> RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		java.util.List<Stmt> sl = (java.util.List<Stmt>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 sl.add(s); RESULT = sl; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt_list",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // func_call ::= T_id T_lpar T_rpar 
            {
              FuncCall RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		java.lang.String id = (java.lang.String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 RESULT = new FuncCall(id); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("func_call",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // func_call ::= T_id T_lpar expr expr_list T_rpar 
            {
              FuncCall RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		java.lang.String id = (java.lang.String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int elleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int elright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		java.util.List<Expr> el = (java.util.List<Expr>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new FuncCall(id, e, el); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("func_call",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expr_list ::= 
            {
              java.util.List<Expr> RESULT =null;
		 RESULT = new LinkedList<Expr>(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_list",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expr_list ::= expr_list T_comma expr 
            {
              java.util.List<Expr> RESULT =null;
		int elleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int elright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		java.util.List<Expr> el = (java.util.List<Expr>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 el.add(e); RESULT = el; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_list",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // l_value ::= T_id 
            {
              LValue RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		java.lang.String id = (java.lang.String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new LValue(id); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("l_value",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // l_value ::= T_string 
            {
              LValue RESULT =null;
		int strleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int strright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		java.lang.String str = (java.lang.String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new LValue(str); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("l_value",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // l_value ::= l_value T_lbracket expr T_rbracket 
            {
              LValue RESULT =null;
		int lvleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int lvright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		LValue lv = (LValue)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new LValue(lv, e); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("l_value",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expr ::= T_num 
            {
              Expr RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		java.lang.Integer num = (java.lang.Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new IntConst(num); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expr ::= T_charconst 
            {
              Expr RESULT =null;
		int charconstleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int charconstright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		java.lang.Character charconst = (java.lang.Character)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new CharConst(charconst); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expr ::= l_value 
            {
              Expr RESULT =null;
		int lvleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lvright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		LValue lv = (LValue)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = lv; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expr ::= func_call 
            {
              Expr RESULT =null;
		int fcleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fcright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		FuncCall fc = (FuncCall)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = fc; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expr ::= T_lpar expr T_rpar 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expr ::= T_plus expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expr ::= T_minus expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expr ::= expr T_plus expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new BinOp(BinOp.Operator.PLUS, l, r); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expr ::= expr T_minus expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new BinOp(BinOp.Operator.MINUS, l, r); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expr ::= expr T_times expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new BinOp(BinOp.Operator.TIMES, l, r); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expr ::= expr T_div expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new BinOp(BinOp.Operator.DIV, l, r); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expr ::= expr T_mod expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new BinOp(BinOp.Operator.MOD, l, r); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expr ::= comments 
            {
              Expr RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // cond ::= T_lpar cond T_rpar 
            {
              Cond RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Cond c = (Cond)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = c; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cond",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // cond ::= T_not cond 
            {
              Cond RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Cond c = (Cond)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new CondOp(CondOp.Operator.NOT, c); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cond",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // cond ::= cond T_and cond 
            {
              Cond RESULT =null;
		int lcleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lcright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Cond lc = (Cond)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int rcleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rcright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Cond rc = (Cond)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new CondOp(CondOp.Operator.AND, lc, rc); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cond",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // cond ::= cond T_or cond 
            {
              Cond RESULT =null;
		int lcleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lcright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Cond lc = (Cond)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int rcleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rcright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Cond rc = (Cond)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new CondOp(CondOp.Operator.OR, lc, rc); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cond",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // cond ::= expr T_equals expr 
            {
              Cond RESULT =null;
		int leleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int leright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expr le = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int releft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int reright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expr re = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new CondOp(CondOp.Operator.EQUALS, le, re); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cond",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // cond ::= expr T_hashtag expr 
            {
              Cond RESULT =null;
		int leleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int leright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expr le = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int releft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int reright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expr re = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new CondOp(CondOp.Operator.HASHTAG, le, re); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cond",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // cond ::= expr T_less expr 
            {
              Cond RESULT =null;
		int leleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int leright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expr le = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int releft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int reright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expr re = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new CondOp(CondOp.Operator.LESS, le, re); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cond",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // cond ::= expr T_greater expr 
            {
              Cond RESULT =null;
		int leleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int leright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expr le = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int releft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int reright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expr re = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new CondOp(CondOp.Operator.GREATER, le, re); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cond",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // cond ::= expr T_lessequal expr 
            {
              Cond RESULT =null;
		int leleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int leright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expr le = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int releft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int reright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expr re = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new CondOp(CondOp.Operator.LESS_EQUAL, le, re); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cond",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // cond ::= expr T_moreequal expr 
            {
              Cond RESULT =null;
		int leleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int leright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expr le = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int releft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int reright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expr re = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new CondOp(CondOp.Operator.GREATER_EQUAL, le, re); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cond",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
