
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.hua.dit;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int T_or = 13;
  public static final int T_string = 43;
  public static final int comments = 50;
  public static final int T_char = 3;
  public static final int T_larrow = 41;
  public static final int T_mod = 10;
  public static final int T_if = 8;
  public static final int T_id = 19;
  public static final int T_divide = 23;
  public static final int T_less = 27;
  public static final int T_rpar = 33;
  public static final int T_equals = 25;
  public static final int T_moreequal = 30;
  public static final int T_semicolon = 39;
  public static final int T_lessequal = 29;
  public static final int T_minus = 21;
  public static final int T_rbracket = 35;
  public static final int T_plus = 20;
  public static final int T_different = 26;
  public static final int T_var = 17;
  public static final int EOF = 0;
  public static final int T_comma = 38;
  public static final int error = 1;
  public static final int T_lcurlybracket = 36;
  public static final int T_hashtag = 24;
  public static final int T_nothing = 12;
  public static final int T_escapedchar = 42;
  public static final int int_const = 47;
  public static final int id = 46;
  public static final int T_do = 5;
  public static final int T_return = 15;
  public static final int T_else = 6;
  public static final int T_int = 9;
  public static final int char_const = 48;
  public static final int T_ref = 14;
  public static final int T_rcurlybracket = 37;
  public static final int string_literal = 49;
  public static final int T_then = 16;
  public static final int T_times = 22;
  public static final int T_and = 2;
  public static final int T_not = 11;
  public static final int T_colon = 40;
  public static final int T_comment = 44;
  public static final int T_fun = 7;
  public static final int T_lpar = 32;
  public static final int T_greater = 28;
  public static final int T_while = 18;
  public static final int T_div = 4;
  public static final int T_num = 31;
  public static final int T_lbracket = 34;
  public static final int T_multilinecomment = 45;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "T_and",
  "T_char",
  "T_div",
  "T_do",
  "T_else",
  "T_fun",
  "T_if",
  "T_int",
  "T_mod",
  "T_not",
  "T_nothing",
  "T_or",
  "T_ref",
  "T_return",
  "T_then",
  "T_var",
  "T_while",
  "T_id",
  "T_plus",
  "T_minus",
  "T_times",
  "T_divide",
  "T_hashtag",
  "T_equals",
  "T_different",
  "T_less",
  "T_greater",
  "T_lessequal",
  "T_moreequal",
  "T_num",
  "T_lpar",
  "T_rpar",
  "T_lbracket",
  "T_rbracket",
  "T_lcurlybracket",
  "T_rcurlybracket",
  "T_comma",
  "T_semicolon",
  "T_colon",
  "T_larrow",
  "T_escapedchar",
  "T_string",
  "T_comment",
  "T_multilinecomment",
  "id",
  "int_const",
  "char_const",
  "string_literal",
  "comments"
  };
}

